# ============================================================
# CompileShaders.cmake — GLSL → SPIR-V → C header
#
# Usage:
#   include(CompileShaders)
#   compile_shader(Triangle.vert VERTEX)
#   compile_shader(Triangle.frag FRAGMENT)
#   add_embedded_shader_library(MyShaders Triangle.vert.spv Triangle.frag.spv)
# ============================================================

# Find glslangValidator (part of Vulkan SDK)
find_program(GLSLANG_VALIDATOR
    NAMES glslangValidator glslang
    HINTS
        ENV VULKAN_SDK
        "$ENV{VULKAN_SDK}/bin"
        "$ENV{VULKAN_SDK}/Bin"
        "$ENV{VULKAN_SDK}/Bin32"
        "/usr/bin"
        "/usr/local/bin"
)

if(NOT GLSLANG_VALIDATOR)
    message(WARNING "glslangValidator not found! Shader compilation disabled. "
                    "Install Vulkan SDK or ensure VULKAN_SDK is set.")
else()
    message(STATUS "Found glslangValidator: ${GLSLANG_VALIDATOR}")
endif()

# --- Compile a single shader file to SPIR-V ---
function(compile_shader SHADER_SOURCE STAGE)
    if(NOT GLSLANG_VALIDATOR)
        return()
    endif()

    get_filename_component(SHADER_NAME ${SHADER_SOURCE} NAME_WE)
    set(SPV_OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/Shaders/${SHADER_NAME}.spv")

    if(STAGE STREQUAL "VERTEX")
        set(STAGE_FLAG "vert")
    elseif(STAGE STREQUAL "FRAGMENT")
        set(STAGE_FLAG "frag")
    else()
        set(STAGE_FLAG ${STAGE})
    endif()

    add_custom_command(
        OUTPUT ${SPV_OUTPUT}
        COMMAND ${CMAKE_COMMAND} -E make_directory "${CMAKE_CURRENT_BINARY_DIR}/Shaders"
        COMMAND ${GLSLANG_VALIDATOR} -V -S ${STAGE_FLAG}
                "${CMAKE_CURRENT_SOURCE_DIR}/Shaders/${SHADER_SOURCE}"
                -o "${SPV_OUTPUT}"
        DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/Shaders/${SHADER_SOURCE}"
        COMMENT "Compiling ${SHADER_SOURCE} → SPIR-V"
    )

    # Export the output path to parent scope
    set(SHADER_OUTPUT_${SHADER_NAME} ${SPV_OUTPUT} PARENT_SCOPE)
endfunction()

# --- Generate a C header embedding compiled SPIR-V ---
function(generate_shader_header TARGET_NAME)
    if(NOT GLSLANG_VALIDATOR)
        return()
    endif()

    set(SPV_FILES ${ARGN})
    set(HEADER_PATH "${CMAKE_CURRENT_BINARY_DIR}/Shaders/EmbeddedShaders.h")

    # Build the command to generate the header
    set(GEN_SCRIPT
        "file(WRITE ${HEADER_PATH} \"// Auto-generated by CompileShaders.cmake — DO NOT EDIT\\n#pragma once\\n#include <cstdint>\\n#include <vector>\\n\\n\")"
    )

    foreach(SPV_FILE ${SPV_FILES})
        get_filename_component(NAME ${SPV_FILE} NAME_WE)
        set(VAR_NAME "k_${NAME}_spv")
        set(GEN_SCRIPT "${GEN_SCRIPT}
            file(READ ${SPV_FILE} DATA HEX)
            string(REGEX REPLACE \"(..)\" \"0x\\\\1,\" DATA_HEX \"\${DATA}\")
            file(APPEND ${HEADER_PATH} \"// ${NAME}\\ninline const std::vector<uint32_t> ${VAR_NAME} = {\\n\")
            file(APPEND ${HEADER_PATH} \"\${DATA_HEX}\\n};\\n\\n\")"
        )
    endforeach()

    add_custom_command(
        OUTPUT ${HEADER_PATH}
        COMMAND ${CMAKE_COMMAND} -E make_directory "${CMAKE_CURRENT_BINARY_DIR}/Shaders"
        COMMAND ${CMAKE_COMMAND} -DINPUT_FILES="${SPV_FILES}" -DOUTPUT="${HEADER_PATH}"
                -P "${CMAKE_CURRENT_SOURCE_DIR}/CompileShaders.cmake"
        DEPENDS ${SPV_FILES}
        COMMENT "Generating embedded shader header"
    )

    # Create a custom target that depends on the header
    add_custom_target(${TARGET_NAME} DEPENDS ${HEADER_PATH})
endfunction()
