#!/usr/bin/env python3
"""将 SPIR-V 二进制文件转换为 C++ uint32_t 数组头文件"""
import sys, os, struct

header_path = sys.argv[1]
spv_files = sys.argv[2:]

with open(header_path, 'w') as out:
    out.write('// Auto-generated by spv_to_header.py - DO NOT EDIT\n')
    out.write('#pragma once\n')
    out.write('#include <cstdint>\n')
    out.write('#include <vector>\n\n')

    for spv in spv_files:
        with open(spv, 'rb') as f:
            data = f.read()

        # SPIR-V 文件大小必须是 4 的倍数
        assert len(data) % 4 == 0, f"SPIR-V file size {len(data)} not multiple of 4"

        # 按 uint32_t (little-endian) 读取
        count = len(data) // 4
        words = struct.unpack(f'<{count}I', data)

        # 生成变量名: Triangle.vert.spv → k_Triangle_vert_spv
        basename = os.path.basename(spv)
        name = basename.replace('.spv', '').replace('.', '_')
        var_name = f'k_{name}_spv'

        out.write(f'// {basename} ({len(data)} bytes, {count} words)\n')
        out.write(f'inline const std::vector<uint32_t> {var_name} = {{\n')
        # 每行 8 个值
        for i in range(0, count, 8):
            chunk = words[i:i+8]
            hex_vals = ', '.join(f'0x{w:08X}u' for w in chunk)
            out.write(f'    {hex_vals},\n')
        out.write('};\n\n')
