"""lightmap_key_check.py -- assertions for Tools/gi/lightmap_key_check.ps1 (task 31).

The GBuffer's eighth MRT carries the lightmap key: (uv0.x, uv0.y, objectIndex, 0). This script
checks the key channel itself and measures whether uv0 can serve as the key.

Asserted (properties of the channel):
  1. the key is written exactly where geometry is: its covered-pixel set equals the
     world-position covered-pixel set (sky carries a zero key = "no key");
  2. page values are exact integers in [0, kGPUMaxObjects).

Reported (the two measured open requirements, see the [KNOWN] blocks):
  3. whether a page really identifies ONE spatial object. Measured: only 34 of 49 pages have a
     world AABB under 30% of the scene diagonal, worst page spans 85.7%. Cause: `objectIndex`
     is the DRAW index -- the GPU-driven path batches several meshes into one draw
     (MeshBatcher), so one index can cover distant geometry. A lightmap page id therefore has
     to come from per-vertex data, not from the draw index.
  4. the uv range / inside-[0,1] fraction and the per-page TEXEL COLLISION rate, i.e. how often
     two distinct world points land on the same (page, texel) at a candidate bake resolution.
     Measured: 70.60% at 128x128 (uv0 spans [-1.42, 28.97], only 67% of pixels inside [0,1]).
     uv0 is a tiling coordinate, not an unwrap.

Both reports are the measured reason the remaining task-31 work is "per-vertex lightmap UV plus
page id, generated by a procedural per-object unwrap" rather than "read uv0 from the GBuffer".
They are printed instead of asserted because that follow-up work is what has to make them hold;
turning them into assertions is its acceptance criterion.

Exit code 0 = all assertions pass.
"""
import os
import sys

import numpy as np

W, H = 1920, 1080
KGPU_MAX_OBJECTS = 1024      # kGPUMaxObjects (ShaderTypes.slang)
PAGE_COMPACT_FRAC = 0.30     # per-page world AABB diagonal < 30% of the scene diagonal
PAGE_COMPACT_MIN = 0.90      # ...for at least 90% of the pages with enough pixels
MIN_PAGE_PIXELS = 100        # a page needs this many pixels to take part in the check
COVER_TOL = 0.001            # key coverage may differ from geometry coverage by at most 0.1%
RESOLUTIONS = (128, 256)     # candidate bake resolutions for the collision report


def load(directory, tag, name):
    path = os.path.join(directory, "gi_%s_%s.f16" % (tag, name))
    a = np.fromfile(path, dtype=np.float16).astype(np.float32)
    if a.size != W * H * 4:
        raise SystemExit("unexpected dump size: %s" % path)
    return a.reshape(H, W, 4)


def main():
    directory = sys.argv[1] if len(sys.argv) > 1 else "."
    tag = sys.argv[2] if len(sys.argv) > 2 else "lmkey"
    failures = []

    def verdict(name, ok, detail):
        print("  [%s] %s -- %s" % ("PASS" if ok else "FAIL", name, detail))
        if not ok:
            failures.append(name)

    key = load(directory, tag, "gb_lightmapkey").reshape(-1, 4)
    world = load(directory, tag, "gb_worldpos")[..., :3].reshape(-1, 3)

    geom = np.abs(world).sum(axis=1) > 0
    key_cov = np.abs(key).sum(axis=1) > 0
    print("=== lightmap key channel ===")
    print("  geometry pixels=%d  key pixels=%d  (%.4f%% of the frame)"
          % (geom.sum(), key_cov.sum(), 100.0 * key_cov.mean()))

    diff = abs(float(key_cov.mean()) - float(geom.mean()))
    verdict("the key is written exactly where geometry is", diff <= COVER_TOL,
            "key %.4f%% vs geometry %.4f%% (|diff| %.4f%% <= %.2f%%)"
            % (100.0 * key_cov.mean(), 100.0 * geom.mean(), 100.0 * diff, 100.0 * COVER_TOL))

    if not key_cov.any():
        print("  !! no key pixels -- cannot continue")
        return 1

    uv = key[key_cov, :2]
    page = key[key_cov, 2]
    wp = world[key_cov]
    rp = np.round(page)
    integral = np.abs(page - rp) < 1e-3
    verdict("page values are exact integers", bool(integral.mean() >= 0.999),
            "%.4f%% of key pixels have an integer page" % (100.0 * integral.mean()))
    in_range = (rp >= 0) & (rp < KGPU_MAX_OBJECTS)
    verdict("page values are inside the object-buffer limit", bool(in_range.all()),
            "pages in [%.0f, %.0f] (limit %d), %d distinct"
            % (rp.min(), rp.max(), KGPU_MAX_OBJECTS, len(np.unique(rp))))

    pages = rp.astype(np.int64)
    scene_diag = float(np.linalg.norm(wp.max(axis=0) - wp.min(axis=0)))
    compact = 0
    total = 0
    worst = 0.0
    worst_page = -1
    for p in np.unique(pages):
        m = pages == p
        if m.sum() < MIN_PAGE_PIXELS:
            continue
        total += 1
        diag = float(np.linalg.norm(wp[m].max(axis=0) - wp[m].min(axis=0)))
        ratio = diag / max(scene_diag, 1e-6)
        if ratio > worst:
            worst, worst_page = ratio, int(p)
        if ratio < PAGE_COMPACT_FRAC:
            compact += 1
    print("")
    print("  [KNOWN] a page does NOT always identify one object: %d/%d pages have a world AABB"
          % (compact, total))
    print("          under %.0f%% of the scene diagonal (worst: page %d spans %.1f%%)."
          % (100.0 * PAGE_COMPACT_FRAC, worst_page, 100.0 * worst))
    print("          Cause: objectIndex is the DRAW index -- the GPU-driven path batches several")
    print("          meshes into one draw (MeshBatcher), so one index can cover distant geometry.")
    print("          A lightmap page id must therefore come from PER-VERTEX data, not the draw")
    print("          index. Reported, not asserted (this is the follow-up work's criterion).")

    # ---- 报告项：uv0 到底能不能当光照图键（唯一性）----------------------------------
    u, v = uv[:, 0], uv[:, 1]
    inside = (u >= 0.0) & (u <= 1.0) & (v >= 0.0) & (v <= 1.0)
    print("")
    print("  uv0 range: u [%.3f, %.3f]  v [%.3f, %.3f]  inside [0,1]: %.2f%%"
          % (u.min(), u.max(), v.min(), v.max(), 100.0 * inside.mean()))
    qw = np.round(wp * 4.0).astype(np.int64)     # 0.25-unit quantization = "same surface point"
    for res in RESOLUTIONS:
        tx = np.clip((u * res).astype(np.int64), 0, res - 1)
        ty = np.clip((v * res).astype(np.int64), 0, res - 1)
        colliding = 0
        covered_texels = 0
        for p in np.unique(pages):
            m = pages == p
            cell = (ty[m] << 20) | tx[m]
            order = np.lexsort((qw[m][:, 2], qw[m][:, 1], qw[m][:, 0], cell))
            cell_s, w_s = cell[order], qw[m][order]
            uniq, first = np.unique(cell_s, return_index=True)
            starts = np.append(first, len(cell_s))
            covered_texels += len(uniq)
            for i in range(len(uniq)):
                if np.unique(w_s[starts[i]:starts[i + 1]], axis=0).shape[0] > 1:
                    colliding += 1
        frac = 100.0 * colliding / max(covered_texels, 1)
        print("  [KNOWN] uv0 as key @%dx%d: %d covered texels, %d colliding (%.2f%%)"
              % (res, res, covered_texels, colliding, frac))
    print("          uv0 is a TILING texture coordinate, not a lightmap unwrap: two different")
    print("          surface points routinely share one (page, uv0) texel, so a lightmap keyed")
    print("          this way would blend unrelated surface points. The remaining task-31 work")
    print("          is a procedural per-object unwrap (dominant-axis box projection into six")
    print("          tiles of a page) -- then this collision rate becomes an assertion.")

    if failures:
        print("")
        print("!! %d verdict(s) failed: %s" % (len(failures), ", ".join(failures)))
        return 1
    print("")
    print("all verdicts passed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
