#!/usr/bin/env python3
"""生成 128×128×64 STBN（时空蓝噪声）并输出 C++ 头文件。

算法（每帧独立）：最佳候选点集 → 环面距离场 → 直方图均衡化。
输出 Engine/Render/RT/STBNData.h：4MB（128×128×64 texels × 4B RGBA8，RGB 同值）。
一次性离线运行，产物提交仓库。
"""
import random, os

W, H, FRAMES, POINTS = 128, 128, 64, 128

def torus_dist2(x0, y0, x1, y1):
    """环面平方距离。"""
    dx = min(abs(x0 - x1), W - abs(x0 - x1))
    dy = min(abs(y0 - y1), H - abs(y0 - y1))
    return dx * dx + dy * dy

def best_candidate_points(seed):
    """Mitchell 最佳候选：逐点放置，每步在 10 个候选中选与已有点最小距离最大者。"""
    rng = random.Random(seed)
    pts = [(rng.randrange(W), rng.randrange(H))]
    for _ in range(POINTS - 1):
        best = None; best_d = -1
        for _ in range(10):   # k 候选
            cx, cy = rng.randrange(W), rng.randrange(H)
            d = min(torus_dist2(cx, cy, px, py) for px, py in pts)
            if d > best_d:
                best_d = d; best = (cx, cy)
        pts.append(best)
    return pts

def distance_field(pts):
    """每个 texel 到最近蓝噪声点的环面欧氏距离（平方）表。"""
    dist = [[1 << 60] * H for _ in range(W)]
    for px, py in pts:
        for x in range(W):
            dx2 = min((x - px) % W, (px - x) % W) ** 2
            for y in range(H):
                dy2 = min((y - py) % H, (py - y) % H) ** 2
                d = dx2 + dy2
                if d < dist[x][y]:
                    dist[x][y] = d
    return dist

def histogram_equalize(dist):
    """距离场直方图均衡化：排序取秩归一化到 [0,255]。返回 W*H 长度的 1D 列表。"""
    flat = [d for row in dist for d in row]
    order = sorted(range(len(flat)), key=lambda i: flat[i])
    out = [0] * len(flat)
    n = len(flat)
    for rank, idx in enumerate(order):
        out[idx] = int(rank * 255.0 / (n - 1)) & 0xFF
    return out

def main():
    out_dir = os.path.normpath(os.path.join(os.path.dirname(__file__), "..", "Engine", "Render", "RT"))
    os.makedirs(out_dir, exist_ok=True)
    # 展开为 RGBA8：每 texel 4 字节（RGB=均衡化值同值，A=255），匹配 RGBA8_UNORM 纹理
    rgba = []
    for z in range(FRAMES):
        pts = best_candidate_points(1000 + z)   # 每帧独立种子
        vals = histogram_equalize(distance_field(pts))
        for v in vals:
            rgba.append(v); rgba.append(v); rgba.append(v); rgba.append(255)
    header = os.path.join(out_dir, "STBNData.h")
    with open(header, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by Tools/gen_stbn.py — DO NOT EDIT\n")
        f.write("#pragma once\n#include <cstdint>\n\n")
        f.write("// 128×128×64 RGBA8 时空蓝噪声（1,048,576 texels × 4B = 4MB；RGB 同值, A=255）\n")
        f.write("inline const uint8_t kSTBNData[] = {\n")
        for i in range(0, len(rgba), 12):
            row = ", ".join(str(v) for v in rgba[i:i+12])
            f.write(f"    {row},\n")
        f.write("};\n")
        f.write("inline constexpr uint32_t kSTBNWidth = 128, kSTBNHeight = 128, kSTBNFrames = 64;\n")
    print(f"STBNData.h written: {len(rgba)} bytes = {len(rgba)//4} texels")

if __name__ == "__main__":
    main()
